/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package latihan;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) throws InterruptedException {
        System.out.println(new App().getGreeting());
        HelloRunnable.main(args);
        HelloThread.main(args);
        SleepMessages.main(args);
        SimpleThreads.main(args);
        Deadlock.main(args);
        ProducerConsumerExample.main(args);
    }
}
