/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package latihan;

import latihan.dua.*;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        System.out.println("Check if array exists : ");
        Array_exists o1 = new Array_exists();
        o1.main(args);
        System.out.println("Fold Left : ");
        Array_foldLeft o3 = new Array_foldLeft();
        o3.main(args);
    }
}
