/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kasus;

import java.sql.*;

public class App {

    public static void main(String[] args) throws ClassNotFoundException, SQLException, InstantiationException, IllegalAccessException {

        Class.forName("org.mariadb.jdbc.Driver").newInstance();
        Connection con = DriverManager.getConnection("jdbc:mariadb://localhost/kasusdb", "akbarlaz", "password");

        Statement st = con.createStatement();
        String sql = ("SELECT * FROM members ORDER BY member_id DESC LIMIT 1;");
        ResultSet rs = st.executeQuery(sql);
        if(rs.next()) { 
        int id = rs.getInt("member_id"); 
        String str1 = rs.getString("full_name");

        System.out.println(id);
        System.out.println(str1);
        }

        con.close();

        

        /* Class.forName("org.mariadb.jdbc.Driver");  
        Connection con=DriverManager.getConnection(  
        "jdbc:mariadb://localhost:3306/kasusdb","akbarlaz","password");  
        //here sonoo is database name, root is username and password  
        Statement stmt=con.createStatement();  
        ResultSet rs=stmt.executeQuery("select * from members");  
        rs.first();
        System.out.println(rs.getString(1)); //result is "Hello World!" */

          
    }
}
