/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kasus;

import kasus.Controller.UserController;
import kasus.Controller.UserAnggotaController;
import kasus.Model.User;
import kasus.Model.UserAnggota;
import kasus.View.UserView;
import kasus.View.UserAnggotaView;
import java.util.List;
import java.util.ArrayList;
import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        
        //fetch user record based on his username
        UserAnggota model1 = retrieveUserAnggotaFromDatabase();

        //Create view
        UserAnggotaView view1 = new UserAnggotaView();

        UserAnggotaController controller1 = new UserAnggotaController(model1, view1);

        controller1.updateView();

        //update model data
        controller1.setNamaUserAnggota("John Constantine");
        controller1.updateView();

        Scanner scan = new Scanner(System.in);
        String username, password, nama, alamat;
        System.out.println("Username:");
        username = scan.nextLine();
        System.out.println("Password:");
        password = scan.nextLine();
        System.out.println("Nama");
        nama = scan.nextLine();
        System.out.println("alamat");
        alamat = scan.nextLine();
        List<UserAnggota> members = new ArrayList<UserAnggota>();
        controller1.set
        
        controller1.updateView();

    }

    private static User retreiveUserFromDatabase() {

        User user = new User();
        user.setUsername("panjul");
        user.setPassword("password");
        return user;
    }

    private static UserAnggota retrieveUserAnggotaFromDatabase() {

        UserAnggota user1 = new UserAnggota();
        user1.setUsername("poli");
        user1.setPassword("password");
        user1.setNamaAnggota("nama");
        user1.setAlamatAnggota("alamat");
        return user1;
    }
}
